# Start me with `docker-compose up nginx`, then test with "http://localhost:8080"

wwwdata:
  image: busybox
  volumes:
    - .:/www-data

nginx:
  image: nginx:1.7
  volumes_from:
    - wwwdata
  volumes:
    - docker/nginx/shared/sites-enabled/:/etc/nginx/conf.d/:ro
  ports:
    - 8088:80
  links:
    - phpfpm:webstack_phpfpm

phpfpm:
  image: php:5.6-fpm
  volumes_from:
    - wwwdata
  working_dir: /www-data

